//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWBA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerPhoneNumber
    {
        public int pkID { get; set; }
        public int custID { get; set; }
        public string phoneNumber { get; set; }
        public int phoneTypeCode { get; set; }
        public bool silent { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual phoneTypeLookup phoneTypeLookup { get; set; }
    }
}
