//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWBA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateLookup
    {
        public StateLookup()
        {
            this.customerAddresses = new HashSet<customerAddress>();
        }
    
        public string StateCode { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<customerAddress> customerAddresses { get; set; }
    }
}
