//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWBA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactiontypeCode
    {
        public transactiontypeCode()
        {
            this.transactions = new HashSet<transaction>();
        }
    
        public int code { get; set; }
        public string description { get; set; }
        public double feeAUD { get; set; }
    
        public virtual ICollection<transaction> transactions { get; set; }
    }
}
