//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWBA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int transactionID { get; set; }
        public int transactionType { get; set; }
        public int accountNum { get; set; }
        public Nullable<int> destAccoutNum { get; set; }
        public double amount { get; set; }
        public string comment { get; set; }
        public System.DateTime modifyDate { get; set; }
        public string transactionTypeCode { get; set; }
    
        public virtual account account { get; set; }
        public virtual account account1 { get; set; }
    }
}
