//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWBA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class billPay
    {
        public int billPayID { get; set; }
        public int accountNum { get; set; }
        public int payeeID { get; set; }
        public double amount { get; set; }
        public System.DateTime scheduleDate { get; set; }
        public string periodCode { get; set; }
        public System.DateTime modifyDate { get; set; }
    
        public virtual Payee Payee { get; set; }
        public virtual periodLookup periodLookup { get; set; }
    }
}
