//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWBA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerAddress
    {
        public int pkID { get; set; }
        public int custID { get; set; }
        public string addressline1 { get; set; }
        public string addressline2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string postcode { get; set; }
        public int addressTypeCode { get; set; }
    
        public virtual addressTypeLookup addressTypeLookup { get; set; }
        public virtual customer customer { get; set; }
        public virtual StateLookup StateLookup { get; set; }
    }
}
