//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWBA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public int custID { get; set; }
        public string userid { get; set; }
        public string pass { get; set; }
        public System.DateTime modifydate { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
