//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWBA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NWABEntities : DbContext
    {
        public NWABEntities()
            : base("name=NWABEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<billPay> billPays { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<Payee> Payees { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<transactiontypeCode> transactiontypeCodes { get; set; }
    }
}
