//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWBA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payee
    {
        public Payee()
        {
            this.billPays = new HashSet<billPay>();
        }
    
        public int payeeID { get; set; }
        public string payeeName { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public int bPayCode { get; set; }
        public string phone { get; set; }
    
        public virtual ICollection<billPay> billPays { get; set; }
    }
}
