//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWBA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class periodLookup
    {
        public periodLookup()
        {
            this.billPays = new HashSet<billPay>();
        }
    
        public string periodCode { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<billPay> billPays { get; set; }
    }
}
