//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWBA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class transaction
    {
        [Display(Name = "Transaction Number")]
        public int transactionID { get; private set; }

        [Display(Name = "Transaction Type")]
        public int transactionType { get; set; }

        [Display(Name = "Account Number (From)")]
        public int accountNum { get; set; }

        [Display(Name = "Account Number (To)")]
        public Nullable<int> destAccoutNum { get; set; }

        [Display(Name = "Amount")]
        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "{0:C}", ApplyFormatInEditMode=true)]
        [Required]

        public double amount { get; set; }

        [Display(Name = "Comment")]
        [DataType(DataType.Text)]        
        public string comment { get; set; }

        [Display(Name = "Date Modified")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode=true)]
        public System.DateTime modifyDate { get; set; }
    
        public virtual account account { get; set; }
        public virtual account account1 { get; set; }
        public virtual transactionTypeLookup transactionTypeLookup { get; set; }
    }
}
